### ISSUE TITLE
Html Data View Not Correct

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#13]
**Describe the bug**
The data on the html index page for co-ops uk data is incorrect. The addresses are displayed where the names should be.

**To Reproduce**
Look at https://dev.data.solidarityeconomy.coop/coops-uk/index.html 

**Expected behavior**
The name of each coop should be displayed in the Co-op Name Column

**Comment by wu-lee** [comment]
Looking, I am not sure that I understand - can you give a specific example from that page?  It's sorted alphanumerically (perhaps I mean numeribetically), so that those names with numbers come first, and so do look a bit like addresses in some cases... but I think those are anomalies.   Am I missing something?

**Comment by ColmDC** [comment]
Curious. I should have taken a screen shot, as it looks fine now.
