### ISSUE TITLE
Search panel not opening

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#21]
**Describe the bug**
The search panel is not opening properly

**To Reproduce**
1. Open https://dev.coopsuk.solidarityeconomy.coop/
2. Click on search tab 

**Expected behavior**
The drop down filter options should appear below the search text box.

**Screenshots**

![Search panel not opening properly](https://github.com/DigitalCommons/coopsuk/assets/108667445/1b9a15f1-f5b4-4aed-b4b7-cdae3e08937a)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Firefox - Version [e.g. 22]

**Comment by wu-lee** [comment]
Discovered something like this independently. If you open the browser console, I expect you'll see an error saying such and such field can't be in `filterableFields` because it's not a vocab.

Such-and-such being one or all of `cukSector`, `sicSection` and `locality`.

Two solutions to this - well, four:
- take out those fields from `filtereableFields`, have `primaryActivity` as the first and therefore the directory field.
- revert the mykomap version to 3.0.4
- alter mykomap to either implement the use of non-vocab (i.e. ad hoc) vocabs, or
- alter it to silently drop them from the filters, as 3.0.4 does. This at least allows the directory to show adhoc vocabs. (Tantamount to option 2.)

I've gone for the first one for the moment, should now be redeployed. Which do you prefer?

**Comment by ColmDC** [comment]
>take out those fields from filtereableFields, have primaryActivity as the first and therefore the directory field.
That is fine for now. We can schedule to do "alter mykomap to either implement the use of non-vocab (i.e. ad hoc) vocabs" later. https://github.com/DigitalCommons/mykomap/issues/201
